### ISSUE TITLE
doubt in MLKNN

### ISSUE THREAD

**Issue by Lxinyuelxy** [yaoz08/MLCLAS#2]
you have already count self.ph in here:
```python
self.ph = np.sum(y, axis=0)
```
why you count again:
https://github.com/markzy/MLCLAS/blob/71d890d1e7b214457c25e6a4e0557c6f85e7a6f1/mlclas/ensemble/ensembles.py#L239
and when I comment out the code in line 238 and 239, the accuracy is improved

**Comment by markzy** [comment]
This project is a really old stuff I did.
I'm not an expert about this, here's the original paper, feel free to check it out :)
http://ieeexplore.ieee.org/abstract/document/6471714/?reload=true

**Comment by Lxinyuelxy** [comment]
This is the same paper which  I recently read. And I think you should either remove the code in line 233 or remove the code in line 238 and 239. Both of the results is the same : )

**Comment by markzy** [comment]
Cool, thanks
